# Generated by Django 6.0.2 on 2026-04-13 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPanel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_user', models.CharField(max_length=50, unique=True, verbose_name='AdminUsername')),
                ('admin_passwd', models.CharField(max_length=128, verbose_name='AdminUserpasswd')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='마지막 로그인')),
            ],
            options={
                'verbose_name': '어드민 유저',
                'verbose_name_plural': '어드민 유저 목록',
                'db_table': 'admin_panel',
            },
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(max_length=20, unique=True, verbose_name='유저아이디')),
                ('email', models.EmailField(max_length=350, unique=True, verbose_name='유저이메일')),
                ('nickname', models.CharField(blank=True, default='', max_length=30, verbose_name='유저닉네임')),
                ('password', models.CharField(db_column='passwd', max_length=128, verbose_name='유저비밀번호(Hash)')),
                ('isStaff', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='가입일')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='마지막 로그인 시각')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '일반 유저',
                'verbose_name_plural': '일반 유저 목록',
                'db_table': 'user_panel',
            },
        ),
        migrations.CreateModel(
            name='IshaSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='일정 제목')),
                ('subtitle', models.CharField(blank=True, default='', max_length=200, verbose_name='부제목')),
                ('schedule_date', models.DateField(verbose_name='일정 날짜')),
                ('start_time', models.TimeField(verbose_name='시작 시간')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('color', models.CharField(choices=[('white', '화이트'), ('blue', '블루'), ('sky', '스카이'), ('silver', '실버'), ('soft', '소프트')], default='blue', max_length=20, verbose_name='카드 색상')),
                ('image', models.ImageField(blank=True, null=True, upload_to='schedule/isha/%Y/%m/', verbose_name='이미지')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_isha_schedules', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '이샤 일정',
                'verbose_name_plural': '이샤 일정 목록',
                'db_table': 'isha_schedule',
                'ordering': ['schedule_date', 'sort_order', 'start_time', 'id'],
            },
        ),
        migrations.CreateModel(
            name='NewsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('notice', '공지사항'), ('update', '업데이트'), ('schedule', '일정'), ('archive', '아카이브'), ('important', '중요')], default='notice', max_length=20, verbose_name='카테고리')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('summary', models.CharField(blank=True, default='', max_length=300, verbose_name='추가 내용')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='고정 공지')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '게시글',
                'verbose_name_plural': '게시글 목록',
                'db_table': 'news_post',
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NewsBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('text', '텍스트'), ('image', '이미지')], max_length=10, verbose_name='블록 타입')),
                ('content', models.TextField(blank=True, default='', verbose_name='텍스트 내용')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/images/%Y/%m/', verbose_name='이미지')),
                ('caption', models.CharField(blank=True, default='', max_length=255, verbose_name='이미지 설명')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='정렬 순서')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='isha_project.newspost', verbose_name='게시글')),
            ],
            options={
                'verbose_name': '게시글 블록',
                'verbose_name_plural': '게시글 블록 목록',
                'db_table': 'news_block',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
