# Generated by Django 6.0.2 on 2026-04-13 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isha_project', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='YouTubeChannelCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(default='youtube', max_length=20)),
                ('channel_id', models.CharField(max_length=128, unique=True)),
                ('handle', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('uploads_playlist_id', models.CharField(blank=True, max_length=128)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '유튜브 채널 캐시',
                'verbose_name_plural': '유튜브 채널 캐시 목록',
                'db_table': 'youtube_channel_cache',
            },
        ),
        migrations.CreateModel(
            name='YouTubeLiveCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=128, unique=True)),
                ('is_live', models.BooleanField(default=False)),
                ('video_id', models.CharField(blank=True, max_length=128)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('viewer_count', models.PositiveIntegerField(default=0)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('fetched_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '유튜브 라이브 캐시',
                'verbose_name_plural': '유튜브 라이브 캐시 목록',
                'db_table': 'youtube_live_cache',
            },
        ),
        migrations.CreateModel(
            name='YouTubeVideoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(db_index=True, max_length=128)),
                ('video_id', models.CharField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(default=0)),
                ('view_count', models.BigIntegerField(default=0)),
                ('like_count', models.BigIntegerField(default=0)),
                ('comment_count', models.BigIntegerField(default=0)),
                ('video_type', models.CharField(choices=[('video', '일반 영상'), ('short', '쇼츠'), ('live_archive', '다시보기'), ('clip', '클립')], default='video', max_length=20)),
                ('is_live_content', models.BooleanField(default=False)),
                ('is_upcoming', models.BooleanField(default=False)),
                ('youtube_url', models.URLField(blank=True)),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '유튜브 영상 캐시',
                'verbose_name_plural': '유튜브 영상 캐시 목록',
                'db_table': 'youtube_video_cache',
                'ordering': ('-published_at', '-id'),
            },
        ),
    ]
