# Generated by Django 6.0.2 on 2026-04-13 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isha_project', '0002_youtubechannelcache_youtubelivecache_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youtubevideocache',
            name='video_type',
            field=models.CharField(choices=[('video', '일반 영상'), ('short', '쇼츠'), ('music', '노래')], default='video', max_length=20),
        ),
    ]
