# Generated by Django 6.0.2 on 2026-04-13 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isha_project', '0003_alter_youtubevideocache_video_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubechannelcache',
            name='subscriber_count',
            field=models.BigIntegerField(default=0, verbose_name='구독자 수'),
        ),
    ]
