# Generated by Django 6.0.2 on 2026-04-13 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isha_project', '0004_youtubechannelcache_subscriber_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChzzkVideoCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(db_index=True, max_length=128, verbose_name='채널 ID')),
                ('video_no', models.BigIntegerField(unique=True, verbose_name='영상 번호')),
                ('video_id', models.CharField(blank=True, max_length=128, verbose_name='영상 ID')),
                ('title', models.CharField(max_length=255, verbose_name='제목')),
                ('video_type', models.CharField(choices=[('replay', '다시보기'), ('clip', '클립')], default='replay', max_length=20, verbose_name='영상 타입')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='썸네일 URL')),
                ('duration_seconds', models.PositiveIntegerField(default=0, verbose_name='재생 시간(초)')),
                ('read_count', models.BigIntegerField(default=0, verbose_name='조회수')),
                ('publish_date', models.DateTimeField(blank=True, null=True, verbose_name='업로드 일시')),
                ('category_type', models.CharField(blank=True, max_length=50, verbose_name='카테고리 타입')),
                ('video_category', models.CharField(blank=True, max_length=100, verbose_name='카테고리')),
                ('video_category_value', models.CharField(blank=True, max_length=100, verbose_name='카테고리명')),
                ('chzzk_url', models.URLField(blank=True, verbose_name='치지직 URL')),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True, verbose_name='마지막 동기화')),
            ],
            options={
                'verbose_name': '치지직 영상 캐시',
                'verbose_name_plural': '치지직 영상 캐시 목록',
                'db_table': 'chzzk_video_cache',
                'ordering': ('-publish_date', '-video_no'),
            },
        ),
    ]
