# Generated by Django 6.0.2 on 2026-04-13 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isha_project', '0005_chzzkvideocache'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaverCafePostCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(db_index=True, verbose_name='카페 ID')),
                ('menu_id', models.IntegerField(db_index=True, verbose_name='게시판 ID')),
                ('article_id', models.BigIntegerField(unique=True, verbose_name='게시글 ID')),
                ('board_type', models.CharField(choices=[('notice', '공지'), ('community', '커뮤니티')], default='community', max_length=20, verbose_name='게시판 타입')),
                ('subject', models.CharField(blank=True, max_length=500, verbose_name='제목')),
                ('writer_nickname', models.CharField(blank=True, max_length=100, verbose_name='작성자')),
                ('read_count', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='댓글수')),
                ('like_it_count', models.PositiveIntegerField(default=0, verbose_name='좋아요수')),
                ('write_date_timestamp', models.BigIntegerField(default=0, verbose_name='작성시각(ms)')),
                ('thumbnail_url', models.URLField(blank=True, verbose_name='썸네일')),
                ('cafe_url', models.URLField(blank=True, verbose_name='카페 URL')),
                ('raw_json', models.JSONField(blank=True, default=dict)),
                ('last_synced_at', models.DateTimeField(auto_now=True, verbose_name='마지막 동기화')),
            ],
            options={
                'verbose_name': '네이버 카페 게시글 캐시',
                'verbose_name_plural': '네이버 카페 게시글 캐시 목록',
                'db_table': 'naver_cafe_post_cache',
                'ordering': ('-write_date_timestamp',),
            },
        ),
    ]
