# Generated by Django 6.0.2 on 2026-04-14 06:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isha_project', '0006_navercafepostcache'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='제목')),
                ('content', models.TextField(verbose_name='문의 내용')),
                ('status', models.CharField(choices=[('pending', '답변 대기'), ('answered', '답변 완료'), ('closed', '종료')], default='pending', max_length=20, verbose_name='처리 상태')),
                ('admin_reply', models.TextField(blank=True, default='', verbose_name='관리자 답변')),
                ('is_private', models.BooleanField(default=True, verbose_name='비공개')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='조회수')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정일')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_posts', to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'verbose_name': '문의사항',
                'verbose_name_plural': '문의사항 목록',
                'db_table': 'contact_post',
                'ordering': ['-created_at'],
            },
        ),
    ]
